Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_abq['Year'] = 1990
df_abq.index = pd.to_datetime(df_abq[['Year', 'Month', 'Day', 'Hour']])

ghi_comparison = pd.DataFrame({
    'NC': monthly_ghi,  # using the monthly values from earlier
    'NM': df_abq['GHI'].resample('M').sum(),
})

ghi_comparison.plot.bar()
plt.ylabel('Monthly GHI [W h/m^2]');
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[23], line 2[0m
[1;32m      1[0m df_abq[[38;5;124m'[39m[38;5;124mYear[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;241m1990[39m
[0;32m----> 2[0m df_abq[38;5;241m.[39mindex [38;5;241m=[39m pd[38;5;241m.[39mto_datetime([43mdf_abq[49m[43m[[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mYear[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mMonth[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mDay[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mHour[39;49m[38;5;124;43m'[39;49m[43m][49m[43m][49m)
[1;32m      4[0m ghi_comparison [38;5;241m=[39m pd[38;5;241m.[39mDataFrame({
[1;32m      5[0m     [38;5;124m'[39m[38;5;124mNC[39m[38;5;124m'[39m: monthly_ghi,  [38;5;66;03m# using the monthly values from earlier[39;00m
[1;32m      6[0m     [38;5;124m'[39m[38;5;124mNM[39m[38;5;124m'[39m: df_abq[[38;5;124m'[39m[38;5;124mGHI[39m[38;5;124m'[39m][38;5;241m.[39mresample([38;5;124m'[39m[38;5;124mM[39m[38;5;124m'[39m)[38;5;241m.[39msum(),
[1;32m      7[0m })
[1;32m      9[0m ghi_comparison[38;5;241m.[39mplot[38;5;241m.[39mbar()

[0;31mTypeError[0m: unhashable type: 'list'

